### ISSUE TITLE
Color?

### ISSUE THREAD

**Issue by zarlicho** [tcbegley/cube-solver#6]
Where is the color?

**Comment by tcbegley** [comment]
I'm not sure I understand the question, but the input / output is based on positional labelling of the faces rather than colours (since the colour of the stickers is not really important).

So you have the standard notation:
U - upper
R - right
F - front
D - down
L - left
B - back

You can choose which colours each of those should correspond to. I typically use Blue -> U, Yellow -> R, Red -> F, Green -> D, White -> L, Orange -> B
